#!/usr/bin/env bash
# process-pr-feedback.sh — Two-phase PR feedback processor
#
# Phase 1 — FETCH (script → agent):
#   process-pr-feedback.sh fetch <pr-id-or-url>
#   Outputs all PR comments and tasks as structured JSON to stdout.
#   The agent reads this output, analyzes the current code state,
#   and generates an actions JSON document.
#
# Phase 2 — ACT (agent → script):
#   echo '<actions-json>' | process-pr-feedback.sh act <pr-id-or-url> [--dry-run]
#   Reads actions JSON from stdin and executes: resolve tasks,
#   post replies, create new tasks. Reports a summary to stdout.
#
# Actions JSON format (generated by agent, consumed by act subcommand):
#   {
#     "resolve_tasks": [123, 456],
#     "replies": [
#       { "comment_id": 789, "text": "Good point, fixed in latest commit" }
#     ],
#     "new_tasks": [
#       { "comment_id": 789, "text": "Missing error handling in X" }
#     ]
#   }
#
# Requirements:
#   - BITBUCKET_TOKEN environment variable must be set
#   - curl and jq must be installed
#
# Exit codes:
#   0  Success
#   1  Usage error, missing prerequisites, or invalid JSON input

set -euo pipefail

# ---------------------------------------------------------------------------
# Bootstrap: locate and source bb-api.sh
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -f "${SCRIPT_DIR}/bb-api.sh" ]]; then
    echo "process-pr-feedback: cannot find bb-api.sh in ${SCRIPT_DIR}" >&2
    exit 1
fi

# bb-api.sh itself uses set -euo pipefail; source it in a subshell-safe way
# shellcheck source=bb-api.sh
source "${SCRIPT_DIR}/bb-api.sh"

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

usage() {
    cat >&2 <<EOF
Usage:
  process-pr-feedback.sh fetch <pr-id-or-url>
  process-pr-feedback.sh act   <pr-id-or-url> [--dry-run]

Subcommands:
  fetch     Fetch all PR comments and tasks; output structured JSON to stdout.
  act       Read actions JSON from stdin and execute them against the PR.

Options:
  --dry-run  (act only) Print planned actions without executing any API calls.

Examples:
  # Phase 1: fetch feedback
  process-pr-feedback.sh fetch 2639
  process-pr-feedback.sh fetch https://bitbucket.lab.dynatrace.org/projects/PFS/repos/myrepo/pull-requests/2639

  # Phase 2: execute actions
  echo '{"resolve_tasks":[123],"replies":[{"comment_id":456,"text":"Fixed!"}],"new_tasks":[]}' \\
    | process-pr-feedback.sh act 2639

  # Dry run
  cat actions.json | process-pr-feedback.sh act 2639 --dry-run
EOF
    exit 1
}

# ---------------------------------------------------------------------------
# Argument parsing helpers
# ---------------------------------------------------------------------------

# resolve_pr_args — populate BB_PROJECT, BB_REPO, PR_ID from a PR id or URL
# Sets globals: BB_PROJECT, BB_REPO, PR_ID
resolve_pr_args() {
    local input="$1"

    if [[ "$input" =~ ^https?:// ]]; then
        # Full URL — parse project/repo/id from it
        read -r BB_PROJECT BB_REPO PR_ID <<< "$(bb_parse_pr_url "$input")"
    elif [[ "$input" =~ ^[0-9]+$ ]]; then
        # Bare numeric PR ID — rely on bb_init to populate BB_PROJECT/BB_REPO
        # from git remote (already called before this function)
        PR_ID="$input"
        if [[ -z "${BB_PROJECT:-}" || -z "${BB_REPO:-}" ]]; then
            echo "process-pr-feedback: could not detect project/repo from git remote." >&2
            echo "Either pass the full PR URL, or set BB_PROJECT and BB_REPO." >&2
            exit 1
        fi
    else
        echo "process-pr-feedback: invalid PR argument '${input}'." >&2
        echo "Pass a numeric PR ID or a full Bitbucket PR URL." >&2
        exit 1
    fi
}

# ---------------------------------------------------------------------------
# FETCH subcommand
# ---------------------------------------------------------------------------

cmd_fetch() {
    local pr_arg="$1"

    bb_init
    resolve_pr_args "$pr_arg"

    # Fetch tasks and comments in parallel subshells
    local tasks_json
    local comments_json

    tasks_json=$(bb_get_pr_tasks    "$BB_PROJECT" "$BB_REPO" "$PR_ID")
    comments_json=$(bb_get_pr_comments "$BB_PROJECT" "$BB_REPO" "$PR_ID")

    # ---------------------------------------------------------------------------
    # Build output JSON using jq
    # ---------------------------------------------------------------------------
    # tasks_json   — array of task objects from /tasks endpoint
    # comments_json — array of activity objects (action == "COMMENTED")
    #
    # Task object shape (relevant fields):
    #   { id, state ("OPEN"|"RESOLVED"), text, permittedOperations, ... }
    #   state OPEN → open task; RESOLVED → resolved task
    #
    # Activity/comment object shape (relevant fields):
    #   { id, action:"COMMENTED", comment:{ id, text, author:{name,slug},
    #     comments:[...replies...], anchor:{path,line,...} } }

    jq -n \
        --argjson tasks    "$tasks_json" \
        --argjson comments "$comments_json" \
        '
        # Split tasks by state
        ($tasks | map(select(.state == "OPEN")))      as $open_tasks     |
        ($tasks | map(select(.state == "RESOLVED")))  as $resolved_tasks |

        # Extract comment thread from each activity entry
        ($comments | map(
            .comment as $c |
            {
                id:      $c.id,
                author:  ($c.author.name // $c.author.slug // "unknown"),
                text:    ($c.text // ""),
                file:    ($c.anchor.path  // null),
                line:    ($c.anchor.line  // null),
                # Flatten replies: comments[].comments[] etc. — Bitbucket nests one level
                replies: ($c.comments // [] | map({
                    id:     .id,
                    author: (.author.name // .author.slug // "unknown"),
                    text:   (.text // "")
                }))
            }
        )) as $comment_list |

        {
            open_tasks: ($open_tasks | map({
                id:      .id,
                text:    (.text // ""),
                version: (.version // 0)
            })),
            resolved_tasks: ($resolved_tasks | map({
                id:   .id,
                text: (.text // "")
            })),
            comments: $comment_list,
            summary: {
                open_tasks:     ($open_tasks | length),
                resolved_tasks: ($resolved_tasks | length),
                total_comments: ($comment_list | length)
            }
        }
        '
}

# ---------------------------------------------------------------------------
# ACT subcommand
# ---------------------------------------------------------------------------

cmd_act() {
    local pr_arg="$1"
    local dry_run="${2:-false}"

    bb_init
    resolve_pr_args "$pr_arg"

    # Read actions JSON from stdin
    local actions_raw
    if ! actions_raw=$(cat); then
        echo "process-pr-feedback: failed to read actions JSON from stdin" >&2
        exit 1
    fi

    # Validate JSON
    if ! printf '%s' "$actions_raw" | jq empty 2>/dev/null; then
        echo "process-pr-feedback: invalid JSON on stdin" >&2
        exit 1
    fi

    # Extract action lists (default to empty arrays if missing)
    local resolve_tasks replies new_tasks
    resolve_tasks=$(printf '%s' "$actions_raw" | jq -c '.resolve_tasks // []')
    replies=$(printf '%s'       "$actions_raw" | jq -c '.replies       // []')
    new_tasks=$(printf '%s'     "$actions_raw" | jq -c '.new_tasks     // []')

    local resolved_count=0
    local replied_count=0
    local created_count=0
    local error_count=0

    # -------------------------------------------------------------------------
    # 1. Resolve tasks
    # -------------------------------------------------------------------------
    local task_ids_length
    task_ids_length=$(printf '%s' "$resolve_tasks" | jq 'length')

    for i in $(seq 0 $((task_ids_length - 1))); do
        local task_id
        task_id=$(printf '%s' "$resolve_tasks" | jq -r ".[$i]")

        if [[ "$dry_run" == "true" ]]; then
            echo "[dry-run] Would resolve task ${task_id}"
        else
            # Fetch the current task/comment version for optimistic locking
            local task_version
            task_version=$(_bb_curl GET \
                "${BB_BASE_URL}/projects/${BB_PROJECT}/repos/${BB_REPO}/pull-requests/${PR_ID}/comments/${task_id}" \
                2>/dev/null | jq -r '.version // 0')
            if bb_resolve_task "$BB_PROJECT" "$BB_REPO" "$PR_ID" "$task_id" "$task_version" > /dev/null 2>&1; then
                echo "Resolved task ${task_id}"
                (( resolved_count++ )) || true
            else
                echo "process-pr-feedback: failed to resolve task ${task_id}" >&2
                (( error_count++ )) || true
            fi
        fi
    done

    # -------------------------------------------------------------------------
    # 2. Post replies to existing comments
    # -------------------------------------------------------------------------
    local replies_length
    replies_length=$(printf '%s' "$replies" | jq 'length')

    for i in $(seq 0 $((replies_length - 1))); do
        local comment_id reply_text
        comment_id=$(printf '%s' "$replies" | jq -r ".[$i].comment_id")
        reply_text=$(printf '%s'  "$replies" | jq -r ".[$i].text")

        if [[ "$dry_run" == "true" ]]; then
            echo "[dry-run] Would reply to comment ${comment_id}: ${reply_text}"
        else
            if _bb_add_reply "$comment_id" "$reply_text" > /dev/null 2>&1; then
                echo "Posted reply to comment ${comment_id}"
                (( replied_count++ )) || true
            else
                echo "process-pr-feedback: failed to reply to comment ${comment_id}" >&2
                (( error_count++ )) || true
            fi
        fi
    done

    # -------------------------------------------------------------------------
    # 3. Create new tasks anchored to comments
    # -------------------------------------------------------------------------
    local new_tasks_length
    new_tasks_length=$(printf '%s' "$new_tasks" | jq 'length')

    for i in $(seq 0 $((new_tasks_length - 1))); do
        local anchor_comment_id task_text
        anchor_comment_id=$(printf '%s' "$new_tasks" | jq -r ".[$i].comment_id")
        task_text=$(printf '%s'          "$new_tasks" | jq -r ".[$i].text")

        if [[ "$dry_run" == "true" ]]; then
            echo "[dry-run] Would create task on comment ${anchor_comment_id}: ${task_text}"
        else
            if bb_create_task "$BB_PROJECT" "$BB_REPO" "$PR_ID" "$anchor_comment_id" "$task_text" > /dev/null 2>&1; then
                echo "Created task on comment ${anchor_comment_id}: ${task_text}"
                (( created_count++ )) || true
            else
                echo "process-pr-feedback: failed to create task on comment ${anchor_comment_id}" >&2
                (( error_count++ )) || true
            fi
        fi
    done

    # -------------------------------------------------------------------------
    # Summary
    # -------------------------------------------------------------------------
    if [[ "$dry_run" == "true" ]]; then
        local dry_resolve dry_reply dry_create
        dry_resolve=$(printf '%s' "$resolve_tasks" | jq 'length')
        dry_reply=$(printf '%s'   "$replies"       | jq 'length')
        dry_create=$(printf '%s'  "$new_tasks"     | jq 'length')
        echo ""
        echo "[dry-run] Would resolve ${dry_resolve} tasks, post ${dry_reply} replies, create ${dry_create} new tasks"
    else
        echo ""
        echo "Done: Resolved ${resolved_count} tasks, posted ${replied_count} replies, created ${created_count} new tasks"
        if [[ "$error_count" -gt 0 ]]; then
            echo "Errors: ${error_count} action(s) failed — see stderr for details"
            return 1
        fi
    fi
}

# ---------------------------------------------------------------------------
# Reply helper: POST a comment with a parent reference
# ---------------------------------------------------------------------------
# Bitbucket Server supports threaded replies via the `parent` field.
# bb_add_comment doesn't support this, so we construct the payload directly.

_bb_add_reply() {
    local parent_comment_id="$1"
    local text="$2"

    local payload
    payload=$(jq -n \
        --arg text "$text" \
        --argjson parent_id "$parent_comment_id" \
        '{
            text: $text,
            parent: { id: $parent_id }
        }')

    _bb_curl POST \
        "${BB_BASE_URL}/projects/${BB_PROJECT}/repos/${BB_REPO}/pull-requests/${PR_ID}/comments" \
        --data "$payload"
}

# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

main() {
    if [[ $# -lt 2 ]]; then
        usage
    fi

    local subcommand="$1"
    local pr_arg="$2"
    shift 2

    case "$subcommand" in
        fetch)
            if [[ $# -gt 0 ]]; then
                echo "process-pr-feedback: 'fetch' takes no extra arguments" >&2
                usage
            fi
            cmd_fetch "$pr_arg"
            ;;
        act)
            local dry_run="false"
            for arg in "$@"; do
                case "$arg" in
                    --dry-run) dry_run="true" ;;
                    *)
                        echo "process-pr-feedback: unknown argument '${arg}'" >&2
                        usage
                        ;;
                esac
            done
            cmd_act "$pr_arg" "$dry_run"
            ;;
        *)
            echo "process-pr-feedback: unknown subcommand '${subcommand}'" >&2
            usage
            ;;
    esac
}

main "$@"
